namespace: betagouv
name: oots
version: 1.0.5
readme: README.md
authors:
  - Aurélien Merel <aurelien.merel@beta.gouv.fr>
description: Ansible roles for the European Only-Once Technical System (OOTS)
license: WTFPL
repository: https://github.com/numerique-gouv/ansible-collection-oots
issues: https://github.com/numerique-gouv/ansible-collection-oots/issues
